export const twBase = {
	panel: "min-w-0 rounded-xl border border-black/10 bg-white",
	panelHeader: "border-b border-black/10 bg-[#eef3f8] px-4 py-3",
	rowDivider: "divide-y divide-black/10",
	scrollArea: "max-h-[300px] overflow-y-auto overflow-x-hidden divide-y divide-black/10",
	listRow3: "grid grid-cols-[auto_auto_1fr] items-center gap-3 px-4 py-3 text-sm",
	applyBtn: "h-8 rounded border border-[#cdd6e1] bg-white px-2 text-xs font-semibold text-[#334155] hover:bg-[#f8fafc] disabled:opacity-60",
	miniInput: "h-8 rounded border border-[#cdd6e1] bg-white px-2 text-xs",
	primaryBtn: "h-12 rounded-lg bg-[#015cb9] px-7 text-[15px] font-semibold text-white hover:bg-[#017AF4] transition-colors",
	secondaryBtn: "h-12 rounded-lg border border-[#001830] bg-[#f3f4f6] px-7 text-[15px] font-semibold text-[#001830] hover:bg-[#e8ebf0] transition-colors",
	secondaryBtnSm: "h-[40px] rounded-lg border border-[#001830] bg-[#f3f4f6] px-6 text-[#001830] hover:bg-[#e8ebf0] transition-colors",
	loadingBox: "rounded-lg border border-[#dbe4ef] bg-[#f6f9fc] p-5",
	filterBtnBase: "h-8 rounded-md border px-3 text-xs font-semibold transition-colors",
	filterBtnActive: "border-[#015cb9] bg-[#eef5fd] text-[#015cb9]",
	filterBtnIdle: "border-[#cdd6e1] bg-white text-[#334155] hover:bg-[#f8fafc]",
	searchInput: "h-9 rounded-md border border-[#cdd6e1] bg-white px-3 text-sm text-[#1e1e1e] placeholder:text-[#94a3b8]",
	tableShell: "mt-6 min-h-0 flex-1 overflow-y-auto rounded-xl border border-black/10 bg-white",
	tableHead: "bg-[#eef3f8] text-xs font-semibold uppercase tracking-[0.08em] text-[#334155]",
	tableRow: "border-t border-black/10 text-sm text-[#1e1e1e]",
	iconButton: "flex h-8 w-8 items-center justify-center rounded-md border border-[#cdd6e1] text-lg font-semibold text-[#015cb9] transition-colors hover:bg-[#eef5fd]",
	actionBtnNeutral: "h-8 rounded border border-[#cdd6e1] bg-white px-3 text-xs font-semibold text-[#334155] hover:bg-[#f8fafc] disabled:opacity-60",
	actionBtnDanger: "h-8 rounded border border-[#f3c6c6] bg-white px-3 text-xs font-semibold text-[#b42318] hover:bg-[#fff1f0] disabled:opacity-60",
	actionBtnPrimary: "h-8 rounded bg-[#015cb9] px-3 text-xs font-semibold text-white hover:bg-[#017AF4] disabled:opacity-60",
	pageLayout: "min-h-screen bg-[#f5f5f5]",
	searchPillInput: "h-10 w-full rounded-full border border-[#d9d9d9] bg-white pl-4 pr-10 text-sm text-[#1e1e1e] outline-none",
	cardWhite: "rounded-xl bg-white",
	primaryBtnMd: "h-[42px] rounded-md bg-[#015cb9] px-5 text-[16px] font-medium text-white transition-colors duration-200 hover:bg-[#017AF4]",
};

export const twNav = {
	navShell: "bg-[#E6EAEF] border-b border-gray-300 shadow-sm",
	navContainer: "flex items-center justify-between px-10 py-4",
	navLinks: "flex items-center gap-6 text-gray-600 font-medium",
	navLinkItem: "hover:text-black cursor-pointer transition-colors",
	navDivider: "h-7 w-px bg-gray-300",
	navPillButton: "inline-flex items-center gap-1.5 whitespace-nowrap rounded px-2 py-1 text-sm text-[#1e1e1e] transition-colors hover:bg-[#dce2e9]",
	dropdownMenu: "absolute right-0 mt-2 z-20 w-44 origin-top rounded-md border border-gray-200 bg-white py-1 shadow-lg transition-all duration-200",
	dropdownItem: "block w-full px-3 py-2 text-left text-sm text-[#1e1e1e] hover:bg-[#f2f5f8]",
	dropdownDanger: "block w-full px-3 py-2 text-left text-sm text-[#b42318] hover:bg-[#fff1f0]",
	navbarCartBtn: "relative flex items-center justify-center rounded-full bg-[#015cb9] p-2.5 text-white transition-colors hover:bg-[#017AF4]",
	navbarCartBadge: "absolute -right-1 -top-1 flex h-[18px] min-w-[18px] items-center justify-center rounded-full bg-white px-1 text-[11px] font-bold text-[#015cb9]",
	navbarLoginBtn: "cursor-pointer rounded-md bg-[#015cb9] px-6 py-2 font-medium text-white transition-colors hover:bg-[#017AF4]",
};

export const twFooter = {
	footerShell: "border-t border-gray-300 bg-[#E6EAEF] px-8 py-8 md:px-12",
	footerGrid: "mx-auto grid w-full max-w-6xl grid-cols-1 gap-8 md:grid-cols-[180px_180px_180px_minmax(280px,420px)]",
	footerTitle: "mb-3 text-xl font-semibold text-[#001830]",
	footerLink: "cursor-pointer transition-colors hover:text-[#001830]",
	newsletterInput: "h-10 flex-1 rounded-md border border-[#d9d9d9] bg-white px-3 text-sm text-[#1e1e1e] placeholder:text-[#757575] outline-none focus:border-[#005cb8]",
	newsletterBtn: "h-10 rounded-md bg-[#005cb8] px-4 text-sm font-medium text-white hover:bg-[#004892]",
	checkoutFooterShell: "border-t border-[#d9d9d9] bg-[#d9d9d9]",
	checkoutFooterContainer: "mx-auto flex min-h-[124px] w-full max-w-[1120px] flex-wrap items-center justify-center gap-x-14 gap-y-4 px-6 py-4",
	checkoutInfoTitle: "text-[16px] font-semibold leading-none text-black",
	checkoutInfoText: "text-[12px] font-medium leading-none text-black",
	checkoutMutedText: "pt-2 text-[10px] leading-none text-[#666666]",
};

export const twAuth = {
	authBg: "min-h-screen bg-gradient-to-r from-[#001830] to-[#0a0a0a]",
	authCard: "rounded-lg border border-[#d9d9d9] bg-[#f5f5f5] p-6",
	authInput: "h-10 w-full rounded-md border border-[#d9d9d9] bg-white px-3 text-base text-[#1e1e1e]",
	authPrimaryBtn: "h-12 w-full rounded-md bg-[#015cb9] text-white transition-colors duration-200 hover:bg-[#017AF4] disabled:opacity-60",
	authSecondaryBtn: "h-12 w-full rounded-md border border-[#2c2c2c] bg-[#f5f5f5] text-base text-[#1e1e1e] transition-colors duration-200 hover:bg-white",
};

export const twLayout = {
	pageShell: "min-h-screen bg-[#f5f5f5] flex flex-col",
	pageSection: "mx-auto w-full max-w-4xl flex-1 px-6 py-10",
	cardSoft: "rounded-lg border border-[#dfe5eb] bg-white p-5 shadow-sm",
	adminShell: "mx-auto h-[calc(100dvh-72px)] w-full max-w-[1280px] overflow-hidden px-6 py-6",
	adminContentCard: "min-h-0 overflow-hidden rounded-xl border border-black/10 bg-white p-6 shadow-[0_4px_14px_rgba(0,0,0,0.06)]",
};

export const twCarrito = {
	layout: "flex flex-1 min-h-0 flex-col overflow-hidden bg-[#f5f5f5]",
	section: "mx-auto flex w-full max-w-[1080px] flex-1 min-h-0 flex-col overflow-y-auto px-6 py-8",
	emptyWrap: "flex flex-1 items-start justify-center pt-14",
	emptyCard: "w-full max-w-[520px] rounded-xl border border-black/10 bg-white px-8 py-10 text-center shadow-[0_4px_18px_rgba(0,0,0,0.08)]",
	itemCard: "rounded-md bg-white p-3.5 shadow-[0_2px_6px_rgba(0,0,0,0.15)]",
	summaryCard: "rounded-md bg-white p-4 shadow-[0_2px_6px_rgba(0,0,0,0.15)]",
	checkoutBtn: "mt-4 h-[44px] w-full rounded-md text-[21px] transition-colors duration-200",
	secondaryBtn: "mt-2 h-[40px] w-full rounded-md border border-black/15 bg-[#eef1f4] text-[16px] text-[#001830] transition-colors duration-200 hover:bg-[#e2e7ec] disabled:cursor-not-allowed disabled:opacity-60",
	infoBox: "mt-4 rounded-md border border-[#cfe0f3] bg-[#eef5fd] p-4 text-[#1f3f62] shadow-[0_1px_2px_rgba(0,0,0,0.05)]",
};

export const twCompraConfirmada = {
	layout: "min-h-[calc(100dvh-72px)] bg-[#f5f5f5] flex flex-col",
	section: "mx-auto w-full max-w-4xl flex-1 min-h-0 px-6 py-6 overflow-auto",
	card: "rounded-2xl border border-[#dfe5eb] bg-white p-7 shadow-sm",
	iconWrap: "mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#fff7e8]",
	transferBox: "mx-auto mt-5 max-w-2xl rounded-xl border border-[#e8edf3] bg-[#f8fafc] px-5 py-3 text-[15px] text-[#334155]",
};

export const twCatalogo = {
	productCard: "group flex w-[280px] cursor-pointer flex-col rounded-xl border border-gray-200 bg-white p-4 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-xl",
	productImageWrap: "relative mb-3 flex h-[260px] items-center justify-center overflow-hidden rounded-lg bg-[#f0f0f0]",
	productPromoTag: "absolute left-2 top-2 z-10 rounded-full bg-[#dbe9ff] px-2 py-1 text-[11px] font-semibold text-[#0b3f75]",
	productPrice: "text-2xl font-bold text-slate-900",
	productOldPrice: "ml-2 text-sm text-gray-400 line-through",
	productShippingFree: "mt-1 inline-flex w-fit rounded-full bg-[#E7F7EE] px-2 py-1 text-[12px] font-semibold text-[#1E8E5A]",
	productShippingPlaceholder: "mt-1 inline-flex w-fit invisible rounded-full px-2 py-1 text-[11px] font-semibold",
	whyBuyWrap: "mx-auto mt-14 max-w-6xl rounded-2xl bg-white px-8 py-10 shadow-sm",
	whyBuyTitle: "mb-10 text-center text-3xl font-bold text-[#001830]",
	whyBuyGrid: "grid grid-cols-1 gap-10 md:grid-cols-3",
	whyBuyItemHead: "mb-3 flex items-center gap-3",
	whyBuyIconWrap: "inline-flex size-10 shrink-0 items-center justify-center text-slate-900",
	whyBuyItemTitle: "text-[26px] font-semibold leading-none text-[#001830]",
	whyBuyItemText: "pl-[52px] text-sm text-gray-600",
};

export const twDetalleCelular = {
	detailGalleryWrap: "relative flex h-[360px] items-center justify-center overflow-hidden rounded-xl bg-[#f0f0f0] p-4 sm:h-[400px]",
	detailGalleryImage: "h-[82%] w-auto scale-[1.2] object-contain mix-blend-multiply animate-[fadeIn_260ms_ease-out]",
	detailGalleryArrow: "absolute top-1/2 -translate-y-1/2 rounded-full bg-white/90 px-3 py-1 text-lg text-[#001830] shadow transition-all duration-200 hover:scale-110 hover:bg-white hover:shadow-md active:scale-95 focus:outline-none focus:ring-2 focus:ring-[#015cb9]",
	detailGalleryDot: "h-2.5 w-2.5 rounded-full",
	variationLabel: "mb-2 text-sm font-medium text-[#1e1e1e]",
	variationStorageBtn: "rounded-full px-3.5 py-1.5 text-xs font-medium transition-colors",
	variationStorageActive: "bg-[#015cb9] text-white",
	variationStorageIdle: "bg-[#eef2f7] text-[#4b5563] hover:bg-[#dbe5f1]",
	variationColorBtn: "h-9 w-9 rounded-full border-2 transition-all duration-200",
	variationColorActive: "border-[#015cb9] scale-110 shadow-md",
	variationColorWhite: "border-[#cfd4dc] hover:scale-105 hover:shadow",
	variationColorDefault: "border-white hover:scale-105 hover:shadow",
	detailTitle: "text-[30px] font-semibold leading-tight text-[#1e1e1e]",
	detailPrice: "mt-1.5 text-[42px] font-bold leading-none text-[#1e1e1e]",
	detailShippingFree: "mt-2.5 inline-flex w-fit rounded-full bg-[#E7F7EE] px-3 py-1.5 text-[14px] font-semibold text-[#1E8E5A]",
	detailPromoTag: "mt-2.5 inline-flex rounded-full bg-[#dbe9ff] px-3 py-1 text-[11px] font-semibold uppercase tracking-wide text-[#0b3f75]",
	detailAuxText: "mt-2.5 text-[14px] text-[#4b6b91]",
	detailAuxTextTight: "mt-0.5 text-[14px] text-[#4b6b91]",
	detailDescription: "mt-2.5 text-[14px] leading-relaxed text-[#4b5563]",
	detailSpecs: "mt-3 space-y-1 text-[14px] leading-snug text-[#666]",
};

export const twCheckout = {
	checkoutShell: "h-[calc(100dvh-72px)] bg-[#f5f5f5] flex flex-col overflow-hidden",
	checkoutSection: "mx-auto w-full max-w-[1120px] flex-1 min-h-0 px-6 py-3 overflow-hidden",
	checkoutTopCard: "mt-3 rounded-xl border border-[#dfe5eb] bg-white px-3 py-2 shadow-[0_1px_2px_rgba(0,0,0,0.06)]",
	checkoutStepPillBase: "rounded-full px-2.5 py-0.5 font-semibold",
	checkoutStepPillActive: "bg-[#015cb9] text-white",
	checkoutStepPillIdle: "bg-[#edf2f7] text-[#6b7280]",
	checkoutCard: "rounded-xl border border-[#dfe5eb] bg-white shadow-[0_1px_2px_rgba(0,0,0,0.06)]",
	checkoutCardCompact: "rounded-xl border border-[#dfe5eb] bg-white p-3.5 shadow-[0_1px_2px_rgba(0,0,0,0.06)]",
	checkoutInput: "h-11 rounded-lg border border-[#d5dde6] px-3 text-[15px]",
	checkoutOption: "w-full rounded-xl border p-4 text-left transition-colors",
	checkoutStepGrid: "grid grid-cols-1 gap-6 lg:grid-cols-[1fr_300px]",
	checkoutSummaryTitle: "cursor-pointer font-semibold text-[#001830]",
	checkoutSummaryText: "mt-2 text-sm text-[#1e1e1e]",
	checkoutMethodCard: "w-full rounded-xl border p-4 text-left transition-colors",
	checkoutMethodActive: "border-[#015cb9] bg-[#eef4fb]",
	checkoutMethodIdle: "border-[#d9d9d9] bg-white hover:bg-[#f7fbff]",
	checkoutModalOverlay: "fixed inset-0 z-50 flex items-center justify-center bg-black/45 px-4",
	checkoutModalCard: "w-full max-w-[760px] rounded-xl bg-white p-7 shadow-2xl",
	checkoutModalTitle: "text-[30px] font-bold leading-none text-[#001830]",
	checkoutModalSectionTitle: "text-[17px] font-semibold text-[#001830]",
	checkoutModalItemRow: "flex items-center justify-between gap-3",
	checkoutModalItemAmount: "text-[16px] font-semibold",
	checkoutModalTotal: "text-[30px] font-extrabold leading-none text-[#001830]",
	checkoutPrimaryBtnSm: "h-[42px] rounded-lg px-6 text-[15px] text-white transition-colors",
	checkoutSidebarAside: "lg:sticky lg:top-0 lg:h-fit lg:self-start",
	checkoutSidebarCard: "rounded-xl border border-[#dfe5eb] bg-white p-3.5 shadow-[0_1px_2px_rgba(0,0,0,0.06)]",
	checkoutSidebarStepLabel: "text-[15px] text-[#4b5563]",
	checkoutSidebarDesc: "mt-1 font-semibold text-[#001830]",
	checkoutSidebarItems: "mt-3 space-y-2 border-t border-[#e6ecf2] pt-3",
	checkoutSidebarPriceBox: "mt-3 border-t border-[#e6ecf2] pt-3 text-[14px] text-[#1e1e1e]",
	checkoutSidebarTotal: "mt-1 text-[23px] font-extrabold leading-none text-[#001830]",
	checkoutBackLink: "inline-flex w-fit text-[14px] font-medium text-[#001830] transition-colors hover:text-[#015cb9]",
	checkoutEnvioGrid: "grid h-full min-h-0 grid-cols-1 gap-4 lg:grid-cols-[1fr_300px]",
	checkoutEnvioPanel: "flex h-full min-h-0 flex-col p-4",
	checkoutEnvioLabel: "mt-2 text-[15px] text-[#1e1e1e]",
	checkoutEnvioSearchInput: "h-9 flex-1 rounded-full border border-[#d5dde6] bg-white px-4 text-[14px]",
	checkoutEnvioScrollable: "mt-3 min-h-0 flex-1 overflow-y-auto pr-1",
	checkoutEnvioOptionCard: "cursor-pointer rounded-xl border-2 bg-white p-3 shadow-[0_1px_2px_rgba(0,0,0,0.06)]",
	checkoutEnvioOptionActive: "border-[#015cb9]",
	checkoutEnvioOptionIdle: "border-[#e6ecf2]",
	checkoutEnvioOptionTitle: "text-[17px] font-semibold text-[#1e1e1e]",
	checkoutEnvioOptionText: "text-sm text-[#4b5563]",
	checkoutEnvioOptionPrice: "mt-1.5 text-[20px] font-extrabold leading-none",
	checkoutEnvioPriceFree: "text-[#1E8E5A]",
	checkoutEnvioPriceDefault: "text-[#001830]",
	checkoutEnvioAddressExpand: "overflow-hidden transition-all duration-300 ease-out",
	checkoutEnvioAddressExpandOpen: "mt-3 max-h-[420px] border-t border-[#e6ecf2] pt-3 opacity-100",
	checkoutEnvioAddressExpandClosed: "max-h-0 border-t-0 pt-0 opacity-0",
	checkoutEnvioAddressBox: "mt-2 rounded-lg border border-[#dfe5eb] bg-[#f8fafc] p-2.5",
	checkoutEnvioAddressTitle: "text-[13px] font-semibold text-[#1e1e1e]",
	checkoutEnvioAddressRadios: "mt-2 flex flex-col gap-2 text-sm",
};

export const twAdmin = {
	adminSectionTitle: "text-2xl font-bold text-[#001830]",
	adminSectionSubtitle: "mt-1 text-sm text-[#5b6673]",
	adminCard: "rounded-xl border border-black/10 bg-white p-4 shadow-[0_2px_8px_rgba(0,0,0,0.06)]",
	adminSubCard: "rounded-md border border-[#dbe4ef] bg-[#f8fafc] p-3",
	adminWhiteCard: "rounded border border-[#dbe4ef] bg-white p-3",
	adminInput: "h-9 rounded border border-[#cdd6e1] px-2 text-sm",
	adminTextarea: "w-full rounded border border-[#cdd6e1] px-2 py-2 text-sm",
	adminGhostBtn: "h-8 rounded border border-[#cdd6e1] bg-white px-3 text-xs font-semibold text-[#334155] hover:bg-[#f8fafc]",
	adminDangerBtnXs: "h-7 rounded border border-[#f3c6c6] px-2 text-xs font-semibold text-[#b42318]",
	adminDangerBtnSm: "h-9 rounded border border-[#f3c6c6] px-3 text-xs font-semibold text-[#b42318]",
	adminPrimaryBtnSm: "h-9 rounded-md bg-[#015cb9] px-4 text-sm font-semibold text-white hover:bg-[#017AF4] disabled:opacity-60",
	adminModalOverlay: "fixed inset-0 z-50 flex items-center justify-center bg-black/35 px-4",
	adminModalCard: "w-full max-w-md rounded-lg bg-white p-5 shadow-xl",
	adminModalTitle: "text-xl font-semibold text-[#001830]",
	adminModalText: "mt-2 text-sm text-[#475569]",
	adminModalActions: "mt-5 flex justify-end gap-2",
	adminExpandWrap: "space-y-3",
	adminExpandMetaGrid: "grid grid-cols-1 gap-2 text-sm text-[#1e1e1e] md:grid-cols-2",
	adminHintText: "w-full text-xs text-[#64748b]",
};

export const twResultadoPago = {
	layout: "min-h-[calc(100dvh-72px)] bg-[#f5f5f5] flex flex-col",
	section: "mx-auto w-full max-w-5xl flex-1 min-h-0 px-6 py-6 overflow-auto",
	card: "rounded-3xl border border-[#dfe5eb] bg-white p-7 shadow-[0_12px_28px_rgba(0,24,48,0.08)] md:p-8",
	detailBox: "mx-auto mt-4 w-full max-w-2xl rounded-xl border border-[#dfe5eb] bg-[#f8fafc] p-4 text-left",
	detailItem: "rounded-lg border border-[#e5ebf2] bg-white p-3",
	detailGrid: "mt-1 grid grid-cols-1 gap-1 text-[14px] text-[#334155] sm:grid-cols-2",
	actions: "mt-6 flex flex-col items-center justify-center gap-3 sm:flex-row",
	info: "mx-auto mt-5 max-w-2xl rounded-xl border border-[#e8edf3] bg-[#f8fafc] px-5 py-3 text-center text-[15px] text-[#334155]",
};

export const twDetallePedido = {
	layout: "min-h-screen bg-[#f5f5f5] flex flex-col",
	section: "mx-auto w-full max-w-5xl flex-1 px-6 py-10",
	panel: "rounded-lg border border-[#dfe5eb] bg-white p-5 shadow-sm",
	productRow: "grid grid-cols-[108px_1fr_auto] items-center gap-3 rounded-md bg-[#f8fafc] p-2.5 text-sm text-[#1e1e1e]",
	paymentItem: "rounded-lg border border-[#e5ebf2] bg-[#f8fafc] p-3",
	paymentGrid: "mt-1 grid grid-cols-1 gap-1 text-[14px] text-[#334155] sm:grid-cols-2",
	primaryBtn: "h-10 rounded-md px-4 text-sm font-semibold text-white transition-colors",
};
